// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-2R_B36otoSWY2Viq6pkzBPYg-F3y81A',
    appId: '1:313464506657:web:3bf36b1334a24da5991660',
    messagingSenderId: '313464506657',
    projectId: 'flowercenterdb',
    authDomain: 'flowercenterdb.firebaseapp.com',
    storageBucket: 'flowercenterdb.firebasestorage.app',
    measurementId: 'G-NNJC4CM85F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8aGIJ3SZPDqAs0YwRLqXjIgQp8WkcmwM',
    appId: '1:313464506657:android:97e5c2c0ad8f3fd6991660',
    messagingSenderId: '313464506657',
    projectId: 'flowercenterdb',
    storageBucket: 'flowercenterdb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-VgJIsLsKp6_H9lWUHvSQul3U0duJogc',
    appId: '1:313464506657:ios:9bf6f7c0c7f8b213991660',
    messagingSenderId: '313464506657',
    projectId: 'flowercenterdb',
    storageBucket: 'flowercenterdb.firebasestorage.app',
    iosBundleId: 'com.example.flowercenterdb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-VgJIsLsKp6_H9lWUHvSQul3U0duJogc',
    appId: '1:313464506657:ios:9bf6f7c0c7f8b213991660',
    messagingSenderId: '313464506657',
    projectId: 'flowercenterdb',
    storageBucket: 'flowercenterdb.firebasestorage.app',
    iosBundleId: 'com.example.flowercenterdb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-2R_B36otoSWY2Viq6pkzBPYg-F3y81A',
    appId: '1:313464506657:web:d4e31bf0b6e60c6c991660',
    messagingSenderId: '313464506657',
    projectId: 'flowercenterdb',
    authDomain: 'flowercenterdb.firebaseapp.com',
    storageBucket: 'flowercenterdb.firebasestorage.app',
    measurementId: 'G-WCYMVJ3HXY',
  );
}
