// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDszu6AZdekiBL9ZHk8g0ooB-RU4840Goo',
    appId: '1:989803453980:web:cc1591327e5542fab0c9d9',
    messagingSenderId: '989803453980',
    projectId: 'flower-center-crm',
    authDomain: 'flower-center-crm.firebaseapp.com',
    storageBucket: 'flower-center-crm.firebasestorage.app',
    measurementId: 'G-C9KM33K5TF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWnt6ZACgA7NTXRJRmdoW4U7om0qQ9sHc',
    appId: '1:989803453980:android:85787ae6d652a90ab0c9d9',
    messagingSenderId: '989803453980',
    projectId: 'flower-center-crm',
    storageBucket: 'flower-center-crm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASK87b2QfNeHQKI-snfLwVn2RxaFASoQ4',
    appId: '1:989803453980:ios:98b438122a502625b0c9d9',
    messagingSenderId: '989803453980',
    projectId: 'flower-center-crm',
    storageBucket: 'flower-center-crm.firebasestorage.app',
    iosBundleId: 'ae.flowercenter.crm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASK87b2QfNeHQKI-snfLwVn2RxaFASoQ4',
    appId: '1:989803453980:ios:ce724bdb7f648139b0c9d9',
    messagingSenderId: '989803453980',
    projectId: 'flower-center-crm',
    storageBucket: 'flower-center-crm.firebasestorage.app',
    iosBundleId: 'com.example.flowercenterdb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDszu6AZdekiBL9ZHk8g0ooB-RU4840Goo',
    appId: '1:989803453980:web:12171ced73e22a31b0c9d9',
    messagingSenderId: '989803453980',
    projectId: 'flower-center-crm',
    authDomain: 'flower-center-crm.firebaseapp.com',
    storageBucket: 'flower-center-crm.firebasestorage.app',
    measurementId: 'G-VZY36JQWHK',
  );

}